[package]
name = "game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game"

[dependencies]
lib = { path = "../lib" }

avian3d = { workspace = true }
bevy = { workspace = true }
bevy_egui = { workspace = true }
noisy_bevy = { workspace = true }
